name: Build and Push ARC Runner Image

on:
  push:
    branches:
      - master
    paths:
      - 'Dockerfile'
      - '.github/workflows/push-to-dockerhub.yml'
  workflow_dispatch:
jobs:
  build:
    runs-on: gkedev-2026
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: tespkg
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          # 请根据你的 Docker Hub 仓库名修改此处。
          # 例如: tespkg/arc-runner:v1
          tags: |
            tespkg/arc-runner:latest
            tespkg/arc-runner:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
